import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

//importing radix ui themes
import "@radix-ui/themes/styles.css";
import { Theme, ThemePanel } from "@radix-ui/themes";

//importing clerkprovider
import { ClerkProvider } from "@clerk/nextjs";
import { dark } from "@clerk/themes";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <ClerkProvider
      appearance={{
        baseTheme: dark,
      }}
    >
      <html lang="en">
        <body className={inter.className}>
          <Theme accentColor="grass">
            {children}
            <ThemePanel />
          </Theme>
        </body>
      </html>
    </ClerkProvider>
  );
}
